Repository IBM/go-repo-template, pull requests merged in 2019-11, with the labels that each got.

#33 add more details for dev doc.
  docs/development.md
Labels: approved, lgtm, size/S

#32 Dvernier add githook check
  Makefile
  common/Makefile.common.mk
  common/config/.hadolint.yml
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
Labels: approved, lgtm, size/M

#34 Add cond to not push coverage report when locally
  Makefile
  common/scripts/codecov.sh
Labels: approved, lgtm, size/XS

#35 Check ifdef MARKDOWN_LINT_WHITELIST
  Makefile
  common/Makefile.common.mk
Labels: approved, lgtm, size/XS

#36 The hooks were not automatically installed
  common/Makefile.common.mk
Labels: approved, lgtm, size/S

#37 Added hack.
  hack/.golint_failures
  hack/boilerplate.go.txt
  hack/update-gofmt.sh
  hack/verify-docfiles.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
Labels: approved, lgtm, size/L
