Repository IBM/go-repo-template, pull requests merged in 2019-10, with the labels that each got.

#11 update makefile.
  Makefile
  common/Makefile.common.mk
Labels: approved, lgtm, size/S

#12 make GIT_HOST be overwritten.
  Makefile
Labels: approved, lgtm, size/XS

#13 update makefile to support local build.
  Makefile
Labels: approved, lgtm, size/M

#15 support mac developers
  Makefile
  README.md
  common/Makefile.common.mk
Labels: approved, lgtm, size/S

#16 tag and push latest image.
  Makefile
Labels: approved, lgtm, size/XS

#17 Codecov
  Makefile
  README.md
  common/scripts/codecov.sh
  go.sum
  pkg/stringutil/reverse.go
Labels: approved, lgtm, size/L

#18 test codecov.
  common/scripts/codecov.sh
  pkg/stringutil/palindromic.go
Labels: approved, lgtm, size/S

#19 add tructed registry for dockerfile linter.
  common/config/.hadolint.yml
Labels: approved, lgtm, size/XS

#20 add details of linting tools and download link
  README.md
  docs/development.md
  pkg/stringutil/palindromic.go
Labels: approved, lgtm, size/S

#27 ignore dco for internal user, change cla to dco
  .github/dco.yml
  CONTRIBUTING.md
Labels: approved, lgtm, size/S

#29 update go build script.
  common/scripts/gobuild.sh
Labels: approved, lgtm, size/XS

#31 add linter version.
  docs/development.md
Labels: approved, lgtm, size/M
